
<div id="tabs" class="wide">
  <ul>
    <li><a href="#legal"><span><?php echo __('Terms of Business') ?></span></a></li>
    <li><a href="#general"><span><?php echo __('General') ?></span></a></li>
    <li><a href="#payment"><span><?php echo __('Payment') ?></span></a></li>
    <li><a href="#password"><span><?php echo __('Password') ?></span></a></li>
  </ul>
  <div id="legal">
  	<p>
    <?php 
		if($v->wizard) {      
      		echo __('Thanks for signing up!').' ';
        	echo __('Below, you can read the Terms and Conditions of our Affiliates program.').' ';
        	echo __('Please read through them, and indicate your agreement by clicking the button at the bottom.').' ';
        	echo __('Once you have done that, we will need to get some contact details, and then your account will be fully active.').' ';
      	} else { 
      		echo __('For your reference, here are the terms and conditions for our affiliate program:');
    
		} 
	?>
	</p>

          <?php if($v->wizard) { ?>

            <form method="post">
   <table class="form">
      <tr>
        <td><span class="scrollArea"><?php echo $v->terms ?></span></td>
      </tr>
      <tr>
        <td class="submit">


              <input id="agree" type="submit" value="<?php echo __('I Agree') ?>"/>
                      </td>
      </tr>
    </table>

            </form>
          <?php 
		  	} else {
      echo  "<table class=\"form\"><tr><td><span class=\"scrollArea\">";
      echo $v->terms;
      echo "</span></td></tr></table>";
      echo __('Thank you, we look forward to doing business with you.');
            } 
		  ?>

  </div>
  <div id="general">
    <form method="post">
      <table class="form">
        <tr>
          <td><?php echo __('Affiliate ID:') ?></td>
          <td><?php echo $v->user_id ?></td>
        </tr>
        <tr>
          <td><?php echo __('Email:') ?></td>
          <td id="useremail"><?php echo $v->user_email ?></td>
        </tr>
        
           <tr>
            <td><?php echo __('Referring ID:') ?></td>
            <td><?php echo $v->parent_id ?></td>
        </tr>
        <tr>
          <td><?php echo __('Your Name:') ?></td>
          <td>
            <table>
              <tr>
                <td><?php echo __('Title:') ?></td>
                <td class="spacer"><?php echo __('First Name:') ?></td>
                <td><?php echo __('Last Name:') ?></td>
              </tr>
              <tr>
                <td>
                  <input id="title" name="title" type="text" size="4"
                    value="<?php echo htmlspecialchars($v->user_title) ?>">
                </td>
                <td class="spacer">
                  <input id="firstname" name="first_name" type="text" size="10"
                    value="<?php echo htmlspecialchars($v->user_first_name) ?>">
                  *
                </td>
                <td>
                  <input id="lastname" name="last_name" type="text" size="10"
                    value="<?php echo htmlspecialchars($v->user_last_name) ?>">
                  *
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td><?php echo __('Your Email Address:') ?></td>
          <td>
            <input id="email" name="email" type="text"
              value="<?php echo htmlspecialchars($v->user_email) ?>"> *
            <br/>
            <input id="email_update" name="email_update" type="checkbox"
              	<?php echo $v->user_email_update ? 'checked="checked"' : '' ?>/>
            	<?php echo __('Check this box to receive order updates by email.') ?>
            <br/>
          </td>
        </tr>
                            <tr>
          <td class="mergeup">&nbsp;</td>
          <td id="message" class="mergeup">&nbsp;</td>
        </tr>


        <tr>

          <td><?php echo __('Street Name:') ?><br><?php echo __('City, State:') ?></td>
          <td>
            <input id="address1" name="address1" type="text"
              value="<?php echo htmlspecialchars($v->user_address1) ?>"> *
            <br/>
            <input id="address2" name="address2" type="text"
              value="<?php echo htmlspecialchars($v->user_address2) ?>"> *
            <br/>
            <input id="address3" name="address3" type="text"
              value="<?php echo htmlspecialchars($v->user_address3) ?>">
            <br/>
            <input id="address4" name="address4" type="text"
              value="<?php echo htmlspecialchars($v->user_address4) ?>">
            <br/>
          </td>
        </tr>
        <tr>
          <td><?php echo __('Your Postcode:') ?></td>
          <td>
            <input id="postcode" name="postcode" type="text"
              value="<?php echo htmlspecialchars($v->user_postcode) ?>"> *
          </td>
        </tr>
        <tr>
          <td><?php echo __('Your Country:') ?></td>
          <td>
            <select id="country" name="country">
              <?php foreach($v->countries as $country) { ?>
                <option value="<?php echo $country['id'] ?>"
                    <?php if($v->user_country == $country['id'])
                        echo('selected="selected"') ?> >

                  <?php echo $country['name'] ?>
                </option>
              <?php } ?>
            </select> *
          </td>
        </tr>
        <tr>
          <td><?php echo __('Your Phone Number:') ?></td>
          <td>
            <input id="phone" name="phone" type="text"
              value="<?php echo htmlspecialchars($v->user_phone) ?>">
          </td>
        </tr>
        <tr>
          <td colspan="2" class="submit">
            <input type="submit" value="<?php echo __('Save Details') ?>"/>
          </td>
        </tr>
      </table>
    </form>

    <p><?php echo __('Fields marked') ?> ‘ * ’ <?php echo __('are required.') ?></p>
  </div>
  <div id="password">
    <form method="post">
      <table class="form">
        <tr>
          <td><?php echo __('New Password:') ?></td>
          <td><input id="chosenpassword" type="password" name="password"/></td>
        </tr>
        <tr>
          <td class="mergedown"><?php echo __('Confirm New Password:') ?></td>
          <td class="mergedown">
            <input id="confirmpassword" type="password" name="confirmpassword"/>
          </td>
        </tr>
        <tr>
          <td class="mergeup">&nbsp;</td>
          <td id="passmessage" class="mergeup">&nbsp;</td>
        </tr>
        <tr>
          <td colspan="2" class="submit">
            <input type="submit" value="<?php echo __('Change Password') ?>"/>
          </td>
        </tr>
      </table>
    </form>
  </div>
  <div id="payment">
    <form method="post">
      <table class="form">
        <tr>
          <td><input id="paypal_checked" name="payment_type" type="radio" value="1" onclick='$("#check_checked").removeAttr("checked"); $("#paypal_checked").attr("checked", "checked");' <?php echo htmlspecialchars($v->paypal_checked) ?> />
          <td><?php echo __('PayPal ID:') ?></td>
          <td><input id="paypalid" type="text" value="<?php echo htmlspecialchars($v->user_paypal) ?>"/>
          </td>
        </tr>
        <tr>
          <td><input id="check_checked" name="payment_type" type="radio" value="2" onclick='$("#paypal_checked").removeAttr("checked"); $("#check_checked").attr("checked", "checked");' <?php echo htmlspecialchars($v->check_checked) ?> />
          <td align="center" colspan="3"><?php echo __('Receive Payments by Check') ?></td>
        </tr>
        <tr>
          <td colspan="3" class="submit">
            <input type="submit" value="Set Payment Method" />
          </td>
        </tr>
      </table>
    </form>

    <p>
    	<?php 
			echo __('The PayPal ID is the email address that you use to log into PayPal.').' ';
			echo '<br>';
			echo __('Example:').' ';
			echo 'paypal@example.com. ';  
			echo __('If you wish to receive payment by check');
			echo ',';
			echo __(' please elect this option. ');
			echo __('Earnings will be accumulated until they are claimed.');
            echo __('<br>Note: Payment by check will incur a small shipping & handling charge.')
		?>	
			
	</p>
  </div>
</div>

<div id="failedtosetpwd" class="dialog" title="<?php echo __('Could not Change Password') ?>"><?php echo __('Please choose a new password and enter it in both the boxes.') ?></div>
<div id="generalset" class="dialog" title="<?php echo __('Settings Updated') ?>"><?php echo __('Your details have been set.') ?></div>
<div id="requiredfields" class="dialog" title="<?php echo __('Required Fields Empty') ?>"><?php echo __('Please complete all required fields, marked') ?> * </div>
<div id="pwdset" class="dialog" title="<?php echo __('Password Changed') ?>"><?php echo __('Your password has been changed.') ?></div>
<div id="paypalset" class="dialog" title="<?php echo __('Details Updated') ?>"><?php echo __('Your information has been set.') ?></div>
<div id="endofwizard" class="dialog" title="<?php echo __('Account Activated') ?>"><?php echo __('Thank you for providing these details. Your account is now active.') ?></div>
