

<div id="tabs" class="wide">
  <ul>
    <li><a href="#query"><span><?php echo __('Date Range') ?></span></a></li>
    <li><a href="#results"><span><?php echo __('Results') ?></span></a></li>
    <li><a href="#details"><span><?php echo __('Payment Details') ?></span></a></li>
  </ul>
  <div id="query">
    <form method="post">
      <table class="form">
        <tr>
          <td><?php echo __('View payments from:') ?></td>
          <td><input id="from" type="text" size="12"/></td>
        </tr>
        <tr>
          <td>to:</td>
          <td><input id="to" type="text" size="12"/></td>
        </tr>
        <tr>
          <td class="submit" colspan="2">
            <input id="display" type="submit" value="<?php echo __('Display') ?>"/>
            <input id="download" type="submit" value="<?php echo __('Download') ?>"/>
          </td>
        </tr>
      </table>
      <div id="addnew"><a href="#"><?php echo __('Add new') ?></a> <?php echo __('payment') ?>.</div>
    </form>
  </div>
  <div id="results">
    <table id="restable" class="form">
    </table>
    <div id="navigation">
      <?php echo __('Page') ?> <span id="currentpage">?</span> <?php echo __('of') ?> <span id="maxpages">?</span>.  <?php echo __('Go to:') ?>
      <a id="previous" href="#"><?php echo __('Previous Page') ?></a>,
      <a id="next" href="#"><?php echo __('Next Page') ?></a>,
      <?php echo __('Page') ?> <span id="pagelist">?</span>.
    </div>
  </div>
  <div id="details">
    <table id="detailstable" class="form">
      <?php foreach($v->fields->get_field_descriptions() as $details) { ?>
        <tr>
          <td><?php echo $details[1] ?></td>
          <td>
            <?php $this->make_data_field($details) ?>
          </td>
        </tr>
      <?php } ?>
      <tr>
        <td class="submit" colspan="2">
          <input id="details_save" type="submit" value="<?php echo __('Save') ?>"/>
          <input id="details_cancel" type="submit" value="<?php echo __('Cancel') ?>"/>
        </td>
      </tr>
    </table>
    <p>
      <?php 
	echo __('Fields marked &lsquo; * &rsquo; are required.');
	echo ' ';
	echo __('If you add a new payment, it will be given a payment number automatically when you click Save.');
      ?>
    </p>
  </div>
</div>

<div id="offstart" class="dialog" title="<?php echo __('No More Data') ?>"><?php echo __('You are already on the first page.') ?></div>
<div id="offend" class="dialog" title="<?php echo __('No More Data') ?>"><?php echo __('You are already on the last page.') ?></div>
<div id="requiredfields" class="dialog" title="`<?php echo __('Required Fields Empty') ?>"><?php echo __('Please complete all required fields marked *.') ?></div>
<div id="dberror" class="dialog" title="<?php echo __('Invalid Data') ?>">?</div>
<div id="saved" class="dialog" title="<?php echo __('Changes Saved') ?>"><?php echo __('The information you entered has been saved.') ?></div>
<div id="confirmdelete" class="dialog" title="<?php echo __('Are you sure?') ?>"><?php echo __('Are you sure you want to delete this record?') ?></div>