<div id="tabs" class="medium">
  <ul>
    <li><a href="#summary"><span><?php echo __('Summary') ?></span></a></li>
    <li><a href="#downloadpayments"><span><?php echo __('Download Payments File') ?></span></a></li>
    <li><a href="#uploadpayments"><span><?php echo __('Upload Completed Payments') ?></span></a></li>
  </ul>
  <div id="summary">
    <table class="form">
      <tr>
        <td><?php echo __('Total Orders:') ?></td>
        <td><?php echo $v->currency.$v->total_orders ?></td>
      </tr>
      <tr>
        <td><?php echo __('Total Commission:') ?></td>
        <td><?php echo $v->currency.$v->total_commission ?></td>
      </tr>
      <tr>
        <td><?php echo __('Commission Paid:') ?></td>
        <td><?php echo $v->currency.$v->total_payments ?></td>
      </tr>
      <tr>
        <td><?php echo __('Commission Payable:') ?></td>
        <td><?php echo $v->currency.$v->total_payable ?></td>
      </tr>
    </table>
  </div>
  <div id="downloadpayments">
    <form method="post">
      <table class="form">
        <tr>
          <td><?php echo __('Download payments up to and including:') ?></td>
          <td><input id="to" type="text" size="12"/></td>
        </tr>
        <tr>
          <td class="submit" colspan="2">
            <input id="download" type="submit" value="<?php echo __('Download') ?>"/>
          </td>
        </tr>
      </table>
    </form>
  </div>
  <div id="uploadpayments">
    <form method="post" enctype="multipart/form-data">
      <table class="form">
        <tr>
          <td><?php echo __('Payments file:') ?></td>
          <td><input type="file" name="file"/></td>
        </tr>
        <tr>
          <td class="submit" colspan="2">
            <input type="submit" value="<?php echo __('Upload') ?>"/>
          </td>
        </tr>
      </table>
    </form>
  </div>
</div>

<?php echo $v->message ?>
