
<div id="tabs" class="wide">
  <ul>
    <li><a href="#details"><span><?php echo __('Link Details') ?></span></a></li>
    <li><a href="#banner"><span><?php echo __('Choose Banner') ?></span></a></li>
  </ul>
  <div id="details">
    <form>
      <span id="defaultbanner" style="display: none"><?php
        echo $v->banners[0]['id'] ?></span>
      <span id="bannerscript" style="display: none"><?php
        echo $v->banner_script ?></span>
      <span id="refparam" style="display: none"><?php
        echo $v->refparam ?></span>
      <span id="dataparam" style="display: none"><?php
        echo $v->dataparam ?></span>
      <table class="form">
        <tr>
          <td class="largecelllabel"><?php echo __('Chosen banner:') ?></td>
          <td class="largecell" colspan="2">
            <img id="chosenbanner" src="servebanner.php"/>
            <input id="changebanner" type="submit" value="<?php echo __('Change') ?>"/>
          </td>
        </tr>
        <tr>
          <td><?php echo __('Campaign ID:') ?></td>
          <td class="mergeright">&nbsp;</td>
          <td class="mergeleft">
            <input id="campaignid" type="text" size="20"/>
          </td>
        </tr>
        <tr>
          <td><?php echo __('Link Target:') ?></td>
          <td class="mergeright">
            <span id="baseurl"><?php echo $v->store_home ?></span>
          </td>
          <td class="mergeleft">
            <input id="linktarget" type="text" size="20"/>
          </td>
        </tr>
        <tr>
          <td class="largecelllabel"><?php echo __('To display your banner, copy this code to your website:') ?></td>
          <td class="largecell" colspan="2">
            <textarea id="code" cols="40" rows="10" readonly="1"></textarea>
          </td>
        </tr>
      </table>
    </form>
  </div>
  <div id="banner">
    <p>
    	<?php 
			echo __('This page shows all the available banners.').' ';
			echo __('Please click the one you would like to use.').' ';
			echo __('You will then be taken back to the Link Details screen').', ';
			echo __('where you can finish creating your affiliate link.').' ';
		?>
	</p>

    <?php foreach($v->banners as $banner) {
        if (isset($banner)) {
        ?>
      <span id="name_<?php echo $banner['id'] ?>" style="display: none"><?php
        echo $banner['name'] ?></span>
      <span id="target_<?php echo $banner['id'] ?>" style="display: none"><?php
        echo $banner['link_target'] ?></span>
      <img id="banner_<?php echo $banner['id'] ?>" class="banner"
        src="servebanner.php?name=<?php echo $banner['name'] ?>"/>
    <?php }} ?>
  </div>
</div>
