<?php 
function daterange_tabdefs() { ?>
<li><a href="#query"><span><?php echo __('Date Range') ?></span></a></li>
<li><a href="#results"><span><?php echo __('Results') ?></span></a></li>

<?php }

function daterange_tabs($name, $download_required) { ?>
<div id="query">
  <form method="post">
    <table class="form">
      <tr>
        <td>
        	<?php 
				$dis = 'View '. $name .' from:';
				echo __($dis);
			?>	
        <td><input id="from" type="text" size="12"/></td>
      </tr>
      <tr>
        <td><?php echo __('to:') ?></td>
        <td><input id="to" type="text" size="12"/></td>
      </tr>
      <tr>
        <td class="submit" colspan="2">
          <input id="display" type="submit" value="<?php echo __('Display') ?>"/>
          <?php if($download_required) { ?>
            <input id="download" type="submit" value="<?php echo __('Download') ?>"/>
          <?php } ?>
        </td>
      </tr>
    </table>
  </form>
</div>
<div id="results">
  <table id="restable" class="form">
  </table>
  <div id="navigation">
    <?php echo __('Page') ?> <span id="currentpage">?</span> <?php echo __('of') ?> <span id="maxpages">?</span>.  <?php echo __('Go to:') ?>
    <a id="previous" href="#"><?php echo __('Previous Page') ?></a>,
    <a id="next" href="#"><?php echo __('Next Page') ?></a>,
    <?php echo __('Page') ?> <span id="pagelist">?</span>.
  </div>
</div>
<?php }

function daterange_dialogs() { ?>

<div id="offstart" class="dialog" title="<?php echo __('No More Data') ?>"><?php echo __('You are already on the first page.') ?></div>
<div id="offend" class="dialog" title="<?php echo __('No More Data') ?>"><?php echo __('You are already on the last page.') ?></div>

<?php }
