<?php ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta http-equiv="X-UA-Compatible" content="IE=8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <link rel="stylesheet" href="site.css"/>
    
		<link type="text/css" href="css/redmond/jquery-ui-1.7.2.custom.css" rel="stylesheet" />	
		<script src="http://www.google.com/jsapi"></script>
<script type="text/javascript">  
        google.load("jquery", "1");
		google.load("jqueryui", "1");
        </script>
    <script type="text/javascript" src="site.js"></script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-781235-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

    <script type="text/javascript" src="<?php echo $this->file ?>.js"></script>
    <title><?php echo $v->title ?></title>
  </head>
  <body>
    <span id="key" style="display: none"><?php echo $v->key ?></span>
    <div id="heading">
      <h1 class="logo"><a title="<?php echo $v->title ?>" href="/"></a></h1>
      <?php if($this->show_menu) require('menu.phtml') ?>
    </div>
