
<div id="tabs" class="narrow">
  <ul>
    <li><a href="#logon"><span><?php echo __('Log On') ?></span></a></li>
    <li><a href="#signup"><span><?php echo __('Sign Up') ?></span></a></li>
  </ul>
  <div id="logon">
    <form method="post">
      <table class="form">
        <tr>
          <td><?php echo __('Email:') ?></td>
          <td><input id="username" type="text" name="username"/></td>
        </tr>
        <tr>
          <td><?php echo __('Password:') ?></td>
          <td><input id="password" type="password" name="password"/>
          <span class="tinytext"><a href="reset.php">Forgot your password?</a></span>
          </td>
        </tr>
        <tr>
          <td colspan="2" class="submit">
            <input type="submit" value="<?php echo __('Log On') ?>"/>
          </td>
        </tr>
      </table>
    </form>
  </div>
  <div id="signup">
    <form method="post">
      <table class="form">
        <tr>
          <td class="mergedown"><?php echo __('Enter referring Email:') ?><br>(**This field is optional.)</td>
          <td class="mergedown">
            <input id="parentuser" type="text" name="parentuser"/>
          </td>
        </tr>
        <tr>
          <td class="mergeup">&nbsp;</td>
          <td id="message2" class="mergeup">&nbsp;</td>
        </tr>
        <tr>
          <td class="mergedown"><?php echo __('Your Email:') ?></td>
          <td class="mergedown">
            <input id="chosenusername" type="text" name="username"/>
          </td>
        </tr>
        <tr>
          <td class="mergeup">&nbsp;</td>
          <td id="message" class="mergeup">&nbsp;</td>
        </tr>

        <tr>
          <td><?php echo __('Choose a password:') ?></td>
          <td>
            <input id="chosenpassword" type="password" name="password"/>
          </td>
        </tr>
        <tr>
          <td class="mergedown"><?php echo __('Confirm password:') ?></td>
          <td class="mergedown">
            <input id="confirmpassword" type="password" name="confirmpassword"/>
          </td>
        </tr>
        <tr>
          <td class="mergeup">&nbsp;</td>
          <td id="passmessage" class="mergeup">&nbsp;</td>
        </tr>

        <tr>
          <td colspan="2" class="submit">
            <input type="submit" value="<?php echo __('Sign Up') ?>"/>
          </td>
        </tr>
      </table>
      <p>
        <a href="http://www.zenobooks.com/affiliate-info">Click here for more information about how our affiliate program works.</a>
      </p>
      <p>
      <?php
	  	echo __('Your Email is used for logging on');
		echo ', '; 
		echo __('but it is not used in your affiliate links.');
		echo __('This means you can keep your Email private');
		echo ', '; 
		echo __('if you want to.');
	   ?>	
		</p>
    </form>
  </div>
</div>

<div id="failedtosignup" class="dialog" title="<?php echo __('Form Incomplete') ?>">
	<?php 
		echo __('Before clicking Sign Up').' ';
		echo __('you will need to choose a username'); 
		echo ', ';
		echo __('that has not been taken already');
		echo ', '; 
		echo __('and then enter the same password in the two other boxes.');
    ?>
    </div>

<div id="failedtologon" class="dialog" title="<?php echo __('Logon Failed') ?>"><?php echo __('The Email and password you entered were not recognised.') ?></div>
